### ISSUE TITLE
Upload the source code in the correct file format

### ISSUE THREAD

**Issue by ghost** [XorbTheCat/Calculator#1]
Welcome to github!, you can directly upload .cs files here so no need to add a text file with the code

**Comment by XorbTheCat** [comment]
Ah, thanks for telling me. Your help is very much appreciated :)

**Comment by TheXorbParadox** [comment]
> Welcome to github!, you can directly upload .cs files here so no need to add a text file with the code

Ah, thanks for telling me. Your help is very much appreciated :)
